version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - wget https://github.com/gohugoio/hugo/releases/download/v0.120.0/hugo_0.120.0_Linux-64bit.tar.gz #downloads hugo 0.120.0
      - tar -xzvf hugo_0.120.0_Linux-64bit.tar.gz #extracts gzipped archive file
      - mkdir -p ~/bin #make bin directory for hugo
      - mv hugo ~/bin/
  pre_build:
    commands:
      - echo Installation done on `date`
  build:
    commands:
      - echo Building...
      - echo Build started on `date`
      - git clone https://github.com/TESU0703793/hugo-on-aws.git #clone hugo-on-aws repo
  post_build:
    commands:
      - echo Build finished on `date`
